services:
  frontend:
    image: ghcr.io/fayebullwinkel/climate-learning/frontend:latest
    restart: unless-stopped
    environment:
      REACT_APP_BACKEND: http://localhost:1337
    ports:
      - "3000:80"

  backend:
    image: ghcr.io/fayebullwinkel/climate-learning/backend:latest
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend/.env:/opt/app/.env
    ports:
      - "1337:1337"