name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/fayebullwinkel/climate-learning:backend-latest

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/fayebullwinkel/climate-learning:frontend-latest